console.log('' == '0')
console.log(0 == '')
console.log(0 == '0')
console.log(false == 'false')
console.log(false == '0')
console.log(false == undefined)
console.log(false == null)
console.log(null == undefined)
console.log(' \t\r\n ' == 0)
